#Tomcat
server:
  port: 8080  #端口号
  tomcat:
    uri-encoding: UTF-8     #设置中文格式
    max-threads: 1000       #最大线程数
    min-spare-threads: 30   #最小线程数
  connection-timeout: 5000  #连接超时时间
  servlet:
    context-path: /   #上下文路径
spring:
  #配置环境
  profiles:
    active: dev
  #jackson时间格式化、时区设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:static/
  servlet:
    multipart:
      enabled: true   #配置文件传输
      max-file-size: 100MB    #单个数据的大小
      max-request-size: 100MB   #总数据的大小
  aop:
    auto: true
    proxy-target-class: true
  rabbitmq:
    #address: 127.0.0.1:5672 #mq的IP和端口
    #host: localhost  #地址
    host: 192.168.1.84
    username: admin #用户名
    #password: 123456 #密码
    password: mObile0817.
    virtual-host: /   #虚拟主机名
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual    #采用手动应答
    publisher-confirms: true    #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true   #消息发送到交换机确认机制，是否返回回调
#redis配置
#redis:
#  database: 0
#  host: 127.0.0.1
#  maxActive: 500
#  maxIdle: 8
#  password: 123456
#  pool:
#    max-active: 500
#    max-idle: 8
#    max-wait: -1
#    min-idle: 0
#    timeout: 10000
#  port: 6379
#  timeOut: 10000
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.daemon.background.model   #扫描pojo

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页
  # pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，
  #分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，
  #可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  #默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;
  params: count=countSql
